FROM golang:1.24.7-alpine

WORKDIR /app

RUN apk add --no-cache git curl gcc musl-dev

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
